-- Add diagnostic/test tables and functions

-- Table for auth testing
CREATE TABLE IF NOT EXISTS auth_tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    test_id TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- RLS for auth_tests
ALTER TABLE auth_tests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own test entries"
    ON auth_tests FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert test entries"
    ON auth_tests FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Function to check if a user exists in the auth.users table
CREATE OR REPLACE FUNCTION public.check_user_exists(user_id_param UUID)
RETURNS INT AS $$
DECLARE
  user_count INT;
BEGIN
  SELECT COUNT(*) INTO user_count FROM auth.users WHERE id = user_id_param;
  RETURN user_count;
END;
$$ LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public;

-- Grant access to the authenticated users
GRANT EXECUTE ON FUNCTION public.check_user_exists TO authenticated;
