-- Supabase SQL setup script for InterviewAI

-- Enable UUID extension for better IDs
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table for storing interview sessions
CREATE TABLE IF NOT EXISTS interviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL,
    topic TEXT NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    end_time TIMESTAMP WITH TIME ZONE,
    duration_seconds INTEGER,
    question_count INTEGER NOT NULL DEFAULT 0,
    conversation_state TEXT NOT NULL,
    day_of_week TEXT,
    interview_count INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    -- Add indexes for better query performance
    CONSTRAINT unique_session_id UNIQUE (session_id),
    CONSTRAINT valid_conversation_state CHECK (conversation_state IN ('opening', 'middle', 'closing', 'completed'))
);

CREATE INDEX idx_interviews_user_id ON interviews(user_id);
CREATE INDEX idx_interviews_created_at ON interviews(created_at);

-- Table for storing interview conversation messages
CREATE TABLE IF NOT EXISTS conversation_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_id BIGINT NOT NULL REFERENCES interviews(id) ON DELETE CASCADE,
    speaker TEXT NOT NULL,
    text TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    sequence INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    -- Add constraints and indexes
    CONSTRAINT valid_speaker CHECK (speaker IN ('AI', 'User')),
    CONSTRAINT unique_message_sequence UNIQUE (interview_id, sequence)
);

CREATE INDEX idx_messages_interview_id ON conversation_messages(interview_id);
CREATE INDEX idx_messages_sequence ON conversation_messages(sequence);

-- Table for storing interview feedback
CREATE TABLE IF NOT EXISTS feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_id BIGINT NOT NULL REFERENCES interviews(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    overall_score INTEGER NOT NULL,
    overall_rating TEXT NOT NULL,
    duration_minutes INTEGER NOT NULL,
    interview_date TEXT NOT NULL,
    assessment_type TEXT NOT NULL,
    position TEXT NOT NULL,
    skills_assessment JSONB NOT NULL,
    ai_feedback_analysis TEXT NOT NULL,
    strengths JSONB NOT NULL, -- Stored as array
    areas_for_improvement JSONB NOT NULL, -- Stored as array
    detailed_analysis JSONB NOT NULL,
    recommendations JSONB NOT NULL, -- Stored as array
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    -- Add constraints and indexes
    CONSTRAINT unique_interview_feedback UNIQUE (interview_id)
);

CREATE INDEX idx_feedback_user_id ON feedback(user_id);
CREATE INDEX idx_feedback_interview_id ON feedback(interview_id);

-- RLS Policies for security

-- Enable Row Level Security
ALTER TABLE interviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversation_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE feedback ENABLE ROW LEVEL SECURITY;

-- Interviews table policies
CREATE POLICY "Users can view their own interviews"
    ON interviews FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own interviews"
    ON interviews FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own interviews"
    ON interviews FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own interviews"
    ON interviews FOR DELETE
    USING (auth.uid() = user_id);

-- Conversation messages table policies
CREATE POLICY "Users can view messages from their interviews"
    ON conversation_messages FOR SELECT
    USING (auth.uid() = (SELECT user_id FROM interviews WHERE id = interview_id));

CREATE POLICY "Users can insert messages to their interviews"
    ON conversation_messages FOR INSERT
    WITH CHECK (auth.uid() = (SELECT user_id FROM interviews WHERE id = interview_id));

-- Feedback table policies
CREATE POLICY "Users can view feedback for their interviews"
    ON feedback FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert feedback for their interviews"
    ON feedback FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update feedback for their interviews"
    ON feedback FOR UPDATE
    USING (auth.uid() = user_id);
